# important paths or links data/model etc.
data_path : './data/atis_intents.csv'
model_path : 'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1'
model_name : 'bert-base-uncased'

# Transformer parameters
MAX_SEQ_LEN : 30
top_k_similar_sentences : 5
